ALTER TABLE coordonée
MODIFY id INT AUTO_INCREMENT;
ALTER TABLE nom_cadeau
MODIFY id INT AUTO_INCREMENT;
ALTER TABLE atelier
MODIFY id INT AUTO_INCREMENT;
ALTER TABLE planification
MODIFY id INT AUTO_INCREMENT;
ALTER TABLE planification
MODIFY id INT AUTO_INCREMENT;
ALTER TABLE livraison
MODIFY id INT AUTO_INCREMENT;
ALTER TABLE lutin
MODIFY id INT AUTO_INCREMENT;
ALTER TABLE enfant
MODIFY id INT AUTO_INCREMENT;
